name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - run: npm ci

    - name: Run lint
      run: npm run lint

    - name: Run validate-html
      run: npm run validate-html

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run e2e tests
      run: npm run test:e2e

    - name: Run check-links
      run: npm run check-links
